#!/bin/bash
# 🚀 Deploy Script - Fix Render Backend Service

echo "🎯 FIXLO - RENDER BACKEND DEPLOYMENT"
echo "=================================================="

echo ""
echo "📋 DEPLOYMENT CHECKLIST:"
echo "1. ✅ Code is ready (all files committed)"
echo "2. 🔄 Need to configure Render service"
echo "3. 🎨 Frontend deployment ready"
echo ""

echo "🔧 WHAT YOU NEED TO DO NOW:"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Create/Update service: fixlo-backend"
echo "3. Configure it as WEB SERVICE with these settings:"
echo ""
echo "   📦 Service Type: Web Service (Node.js)"
echo "   📁 Root Directory: server"
echo "   🔨 Build Command: npm install"
echo "   ▶️  Start Command: node index.js"
echo ""
echo "4. Environment Variables (add these):"
echo "   NODE_ENV=production"
echo "   PORT=10000"
echo "   STRIPE_SECRET_KEY=[your key]"
echo "   STRIPE_PRICE_ID=price_1Rf0cZPQ4Cetf7g6ekd8hPLb"
echo "   MONGO_URI=[your MongoDB connection]"
echo "   JWT_SECRET=[random string]"
echo ""
echo "5. Click 'Manual Deploy' → 'Deploy latest commit'"
echo ""

echo "✅ VERIFICATION:"
echo "After deploy, test these URLs:"
echo "- https://handyman-connect-1-ftz8.onrender.com/api (should return JSON)"
echo "- https://www.handyman-connect.com/api (should work via Vercel proxy)"
echo "- https://www.handyman-connect.com/subscribe (Subscribe button should work)"
echo ""

echo "🎉 SUCCESS = Subscribe button redirects to Stripe checkout!"
echo ""
echo "🆘 Need help? Check the build logs in Render dashboard."
