services:
  - type: web
    name: fixlo-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://fixloapp.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://fixloapp.vercel.app,https://www.fixloapp.com,https://fixloapp.com
